version: "3.7"

services:
  mc:
    image: itzg/minecraft-server:2021.2.0-multiarch
    ports:
    # expose the Minecraft server port outside of container
    - 25565:25565
    environment:
      # REQUIRED for all types
      EULA: "TRUE"
      # Set server type (vs the default of vanilla)
      TYPE: FORGE
      MAX_MEMORY: "6G"
      MAX_BUILD_HEIGHT: 300
      VIEW_DISTANCE: 6
      LEVEL_TYPE: LARGEBIOMES
      MAX_PLAYERS: 15
      CONSOLE: false
      DIFFICULTY: hard
      VERSION: 1.12.2
      FORGEVERSION: 14.23.5.2838
      GENERIC_PACK: /modpacks/RLCraft+Server+Pack+1.12.2+-+Beta+v2.8.2.zip
      GENERIC_PACK_STRIP_DIRS: 1
      DISABLE_HEALTCHECK: true
    volumes:
    # use a named, managed volume for data volume
    - /var/mc-rlcraft:/data
    - /var/modpacks:/modpacks:ro
